name: Build and Deploy OpenPnP

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [8, 9, 10, 11, 12, 13, 14, 15]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        run: mvn -B test
        
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/test'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup JDK 8 for Deployment
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package -DskipTests
        
